# Generated by Django 2.1.2 on 2018-11-27 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contester', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('input', models.CharField(max_length=255, verbose_name='Input\r\n (separated by semicolon)')),
                ('output', models.CharField(max_length=255, verbose_name='Output\r\n (separated by semicolon)')),
                ('maximum_time', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contester.Theme'),
        ),
    ]
