# Generated by Django 2.1.2 on 2018-12-09 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contester', '0004_auto_20181209_0601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('successfully', models.BooleanField()),
                ('message', models.CharField(max_length=50)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contester.Exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contester.User')),
            ],
        ),
    ]
